### ISSUE TITLE
Organizar ida prévia para levantamento de informações(espaço, dormitórios, materiais necessários, comida, logística e recepção

### ISSUE THREAD

**Issue by luisfcosta2015** [RioHackerSpace/HackerCamp#4]

**Comment by luisfcosta2015** [comment]
Vamos inserir os nomes aqui!
Luis Felipe

**Comment by luisfcosta2015** [comment]
QR-Code para trilha;
Praça de Ágora: espaço de debates, arena e roda de conversa. Vamos precisar de arquibancada, vidro, losa, palco, iluminação, som, internet, eletrecidade e suporte de mastros;

Suite Hacker(ver novo nome), dois beliches, frigobar, mesa parede dobrável e internet.

Rio Maker Hacker Garden: apresentações, workshps, espaço do conhecimento, biblioteca, espaço maker, logística de montagem e desmontagem.

Trilha do conhecimento da praça de ágora ao Rio maker hacker garden;

Iluminação e tochas.

Lago, revitalização,

Sisterna para reutilização de água e Biodigestor

**Comment by luisfcosta2015** [comment]
Documento com informações do evento: https://docs.google.com/document/d/12G0tgU9Uc3RHGJzB8JJL2x4u67aFsrvkVoIGUp9kj1Q/edit?usp=sharing

**Comment by feliperodrigues64** [comment]
Alterações na iluminação do espaço: Iluminar acesso da entrada à ponte, ponte, lagos 1 e 2, (2 é atrás do orquidário), iluminar orquidário, Iluminar Camping, Pomar (pomar é depois do camping ao lado da casa 1. Iluminar acesso do Pomar à área antes da pónte (caminho de pedras) e áreas de convicência, ao lado do pomar, antes da ponte, antes da varanda de vidro, ágora, trilha ao orquidário. horta e frente do hacker space.

**Comment by feliperodrigues64** [comment]
Restaurante 1650 Espaço bar disponível. Encomendas com 24hs de antecedência. capacidade para 15 pessoas, preço a combinar. 

[https://www.facebook.com/search/top/?q=Espa%C3%A7o%20Bar%201650](url)

**Comment by luisfcosta2015** [comment]
Arquivo com palestrantes: https://docs.google.com/spreadsheets/d/16dRAGh3Aflhi9X3euXS5y3rPAryaGN0iurem3OjGEOs/edit#gid=0

**Comment by feliperodrigues64** [comment]
Apenas para acompanharmos, sem desejar arquivei este ítem "Ida prévia...". Já efetuei a restauração. Aprendendo sobre a ferramenta para estas finalidades.
